<?php
/*
 * Security & Non-used code removing
 */

remove_action( 'wp_head', 'wp_generator');
remove_action( 'wp_head', 'rsd_link');
remove_action( 'wp_head', 'feed_links',2);
remove_action( 'wp_head', 'feed_links_extra',3);
remove_action( 'wp_head', 'wlwmanifest_link');
remove_action( 'wp_head', 'print_emoji_detection_script',7);
remove_action( 'wp_print_styles', 'print_emoji_styles');
remove_action( 'wp_head', 'rest_output_link_wp_head', 10, 0 );
remove_action('template_redirect', 'rest_output_link_header', 11, 0 ); //remove Link header for rest api
remove_action('template_redirect', 'wp_shortlink_header', 11, 0 ); //remove Link header for shortlink
remove_action( 'wp_head', 'wp_shortlink_wp_head', 10, 0 );
add_filter('pings_open', '__return_false'); //remove X-Pingback header
add_filter( 'script_loader_src', 'remove_src_version', 9999 );
add_filter( 'style_loader_src', 'remove_src_version', 9999 );
add_filter('xmlrpc_enabled', '__return_false');
// ?
remove_action( 'template_redirect', 'rest_output_link_header', 11, 0 );

function remove_src_version( $src ){
	global $wp_version;

	$version_str = '?ver='.$wp_version;
	$version_str_offset = strlen( $src ) - strlen( $version_str );

	if( substr( $src, $version_str_offset ) == $version_str )
		return substr( $src, 0, $version_str_offset );
	else
		return $src;
}

add_filter( 'wp_resource_hints', 'remove_wp_resource_hints');
function remove_wp_resource_hints($urls) {
	return array();
}

add_filter( 'wp_headers', 'remove_unnecessary_header' );
function remove_unnecessary_header($headers) {
	// Remove some headers generated by Apache
	if (function_exists('header_remove')) {
		header_remove('X-Powered-By'); // PHP 5.3+
	}

	return $headers;
}
